# Site settings
title: "Hacquebord & Buckles' Legacy"
email: info@hacquebordbuckles.nl
description: ""
baseurl: ""
url: "http://yourdomain.com"
exclude: [Gemfile, Gemfile.lock]

# Build settings
markdown: kramdown
permalink: pretty
